spring:
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: password
  datasource:
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*.xml
